size = 70 42
length = 7.000000 4.200000
velocity = 0.000000 -20.000000
pressure = 0.000000
temperature = 0.000000
geometry = free
######################################################################
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEIIIIIIEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE####EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEE##EEEE##EEEE##EEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEE###EE##EE###EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEE######EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE####EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEE##EEEEEEEEEEEEE##EEEEEEEEEEEEE##EEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEE#####EEEEEEEE####EEEEEEEE#####EEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEE########################EEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEE######EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEE######EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE####EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE####EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEE##EEEEEEEEEEEEEEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEE##EEEEEEE#
#EEEE####EEEEEEEEE##############################EEEEEEEEE####EEEEEEEE#
#EEEEEEE################EEEEEE######EEEEEEE###############EEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE####EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE####EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE####EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE####EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEE######EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEE########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
######################################################################
