size = 40 100
length = 4.000000 10.000000
velocity = 0.000000 -1.00000
pressure = 0.000000
temperature = 0.000000
geometry = free
###############IIIIIIIIII###############
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEE  EEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEE    EEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEE      EEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEE        EEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEE      EEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEE    EEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEE##EEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEE####EEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEE######EEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEE######EEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEE####EEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
##########OOOOOOOOOOOOOOOOOOOO##########