size = 40 50
length = 0.400000 0.500000
velocity = 0.000000 0.000000
pressure = 0.000000
temperature = 0.000000
geometry = free
########################################
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
###########IIIII########IIIII###########
