size = 50 10
length = 10.000000 1.000000
velocity = 0.000000 0.000000
pressure = 0.000000
temperature = 0.000000
geometry = free
##################################################
IEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEO 
IEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEO
IEEEEEEEEEE##EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEO
IEEEEEEEEE###EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEO
IEEEEEEE###EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEO
IEEEEEEE##EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEO
IEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEO
IEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEO
##################################################