size = 80 30
length = 8.000000 3.000000
velocity = 0.000000 0.000000
pressure = 0.000000
temperature = 0.000000
geometry = free
################################################################################
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
IEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
IEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
IEEEEEEEEEE##########EEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
IEEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
IEEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
###################################################EEEEEEEEEEEEEEE##############
###################################################EEEEEEEEEEEEEEE##############
#EEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
IEEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
IEEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
IEEEEEEEEEE##########EEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
IEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
IEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE##########EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#
################################################################################